apiVersion: appsody.dev/v1alpha1
kind: AppsodyApplication
metadata:
  name: example-appsodyapplication
spec:
  # Add fields here
  applicationImage: openliberty/open-liberty:microprofile-ubi-min
  stack: java-microprofile