apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  name: example-appsodyapplication
spec:
  # Add fields here
  applicationImage: openliberty/open-liberty:microProfile2-ubi-min
  stack: java-microprofile
