apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsody-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: appsody-operator
  template:
    metadata:
      labels:
        name: appsody-operator
    spec:
      serviceAccountName: appsody-operator
      containers:
        - name: appsody-operator
          image: appsody/application-operator:daily
          command:
          - appsody-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "appsody-operator"
