apiVersion: v1
data:
  java-microprofile: ""
  java-spring-boot2: ""
  nodejs: ""
  nodejs-express: ""
  swift: ""
kind: ConfigMap
metadata:
  name: appsody-operator-constants
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: appsody-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: appsody-operator
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  - serviceaccounts
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - '*'
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - '*'
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - get
  - create
- apiGroups:
  - apps
  resourceNames:
  - appsody-operator
  resources:
  - deployments/finalizers
  verbs:
  - update
- apiGroups:
  - appsody.dev
  resources:
  - '*'
  verbs:
  - '*'
- apiGroups:
  - route.openshift.io
  attributeRestrictions: null
  resources:
  - routes
  verbs:
  - '*'  
- apiGroups:
  - serving.knative.dev
  attributeRestrictions: null
  resources:
  - services
  verbs:
  - '*'  
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: appsody-operator
subjects:
- kind: ServiceAccount
  name: appsody-operator
roleRef:
  kind: Role
  name: appsody-operator
  apiGroup: rbac.authorization.k8s.io
---  
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appsody-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: appsody-operator
  template:
    metadata:
      labels:
        name: appsody-operator
    spec:
      serviceAccountName: appsody-operator
      containers:
        - name: appsody-operator
          image: appsody/application-operator:daily
          command:
          - appsody-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "appsody-operator"
