#!/bin/bash
#
# Run this script to collect debug information regarding pods that are not ready

set -Euox pipefail

BIN=oc
LOGS_DIR="/must-gather"
SUB_DIR="pods"

# Get pods that are not ready and their namespaces
PODS=$(${BIN} get pods --all-namespaces -o jsonpath="{.items[?(@.status.containerStatuses[*].ready==false)].metadata.name}")
NAMESPACES=$(${BIN} get pods --all-namespaces -o jsonpath="{.items[?(@.status.containerStatuses[*].ready==false)].metadata.namespace}")

# Puts pods and corresponding names into arrays
PODS=($PODS)
NAMESPACES=($NAMESPACES)

# Describe and get all pods that are not ready
for i in ${!PODS[@]}; do
    mkdir -p ${LOGS_DIR}/${NAMESPACES[$i]}/${SUB_DIR}/${PODS[$i]}
    ${BIN} describe pod ${PODS[$i]} -n ${NAMESPACES[$i]} > ${LOGS_DIR}/${NAMESPACES[$i]}/${SUB_DIR}/${PODS[$i]}/describe.log
    ${BIN} get pod ${PODS[$i]} -n ${NAMESPACES[$i]} -o=yaml > ${LOGS_DIR}/${NAMESPACES[$i]}/${SUB_DIR}/${PODS[$i]}/get.yaml
done